name: "@${{ github.actor }}-workflow"

on:
  pull_request:

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display an environment variable GITHUB_ACTIONS
        run: echo "GITHUB_ACTIONS=${GITHUB_ACTIONS}"

      - name: Show branch name and repository
        run: echo "Repository:${{ github.repository }}, Branch:${{ github.ref }}"

      - name: Show the event that triggered the launch workflow
        run: echo "Event Name:${{ github.event_name }}"
