name: "${{ github.actor }}-workflow"

on:
  pull_request:

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Відобразити змінну середовища GITHUB_ACTIONS
        run: echo "GITHUB_ACTIONS=${GITHUB_ACTIONS}"

      - name: Показати назву гілки та репозиторію
        run: echo "Repository: ${{ github.repository }}, Branch: ${{ github.ref }}"

      - name: Показати подію, яка ініціювала запуск workflow
        run: echo "Event Name: ${{ github.event_name }}"
