name: "${{ github.actor }}-workflow"

on:
  pull_request:

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display an environment variable GITHUB_ACTIONS
        run: echo "GITHUB_ACTIONS=${GITHUB_ACTIONS}"

      - name: Display Repository Name
        run: echo "Repository:${{github.repository}}"
        
      - name: Display Branch Name
        run: echo "Branch:${{github.ref}}"
        
      - name: Show the event that triggered the launch workflow
        run: echo "Event Name:${{github.event_name}}"

